/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package charts;

import Arduino.Arduino;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Usuario
 */
public class Window extends javax.swing.JFrame {
    Arduino Arduino = new Arduino();
    //int i = 0;
    SerialPortEventListener evento = new SerialPortEventListener () {
        @Override
        public void serialEvent(SerialPortEvent spe) {
            if(Arduino.MessageAvailable()==true){
                String oli = Arduino.PrintMessage();
                int it = oli.indexOf(";");
                String tem = oli.substring(0, it);
                String cadena = oli.substring(it+1, oli.length());
                it = cadena.indexOf(";");
                String pre = cadena.substring(0, it);
                String volu = cadena.substring(it+1, cadena.length());
                
                System.out.println(tem);
                System.out.println(pre);
                System.out.println(volu);
                float pref = Float.parseFloat(pre);
                pref = (float) (pref/133.32);
                float volu1 =  (float) ((755.213*50)/pref);
                
                System.out.println("Real:" + volu + "vs Teorico:"+ volu1);
                System.out.println(pref+"mmHg");
                Serie.add(Float.parseFloat(tem),pref);
                Serie2.add(Float.parseFloat(volu),pref);
                Serie3.add(Float.parseFloat(tem),Float.parseFloat(volu));
            }
        }
    };
    final XYSeries Serie = new XYSeries("Presion vs temperatura");
    final XYSeries Serie2 = new XYSeries("Presion vs Volumen");
    final XYSeries Serie3 = new XYSeries("temperatura vs Volumen ");
    final XYSeriesCollection Coleccion = new XYSeriesCollection();
    final XYSeriesCollection Coleccion2 = new XYSeriesCollection();
    final XYSeriesCollection Coleccion3 = new XYSeriesCollection();
    JFreeChart Grafica;
    JFreeChart Grafica2;
    JFreeChart Grafica3;
    
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();

        try {
        Arduino.ArduinoRX("COM3", 2000, 9600, evento);
//            if(Arduino.MessageAvailable()==true){
//                String oli = Arduino.PrintMessage();
//                int it = oli.indexOf(";");
//                String tem = oli.substring(0, it);
//                String cadena = oli.substring(it+1, oli.length());
//                it = cadena.indexOf(";");
//                String pre = cadena.substring(0, it);
//                String volu = cadena.substring(it+1, cadena.length());
//                System.out.println(tem);
//                System.out.println(pre);
//                System.out.println(volu);
//                float pref = Float.parseFloat(pre);
//                pref = (float) (pref/133.32);
//                System.out.println(pref+"mmHg");
//                Serie.add(Float.parseFloat(tem),pref);
//                Serie2.add(pref,Float.parseFloat(volu));
//                Serie3.add(Float.parseFloat(tem),Float.parseFloat(volu));
//            }
        Serie.add(25,750);
        Serie2.add(50,750);
        Serie3.add(0,0);
        Coleccion.addSeries(Serie);
        Coleccion2.addSeries(Serie2);
        Coleccion3.addSeries(Serie3);
        Grafica= ChartFactory.createXYLineChart("Presion vs Temperatura", "Temperatura (C°)", "Presion (mmHg)", Coleccion,PlotOrientation.VERTICAL,true,true,false);
        Grafica2= ChartFactory.createXYLineChart("Presion vs Volumen","Volumen (cm^3)", "Presion (mmHg)", Coleccion2,PlotOrientation.VERTICAL,true,true,false);
        Grafica3= ChartFactory.createXYLineChart("Temperatura vs Volumen", "Temperatura (C°)", "Volumen (cm^3)", Coleccion3,PlotOrientation.VERTICAL,true,true,false);
        
        } catch (Exception e) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE,null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Presion Vs Temperatura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Presion Vs Volumen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Volumen Vs Temperatura ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    ChartPanel Panel = new ChartPanel(Grafica);
    JFrame Ventana = new JFrame("JFreeChart");
    Ventana.getContentPane().add(Panel);
    Ventana.pack();
    Ventana.setVisible(true);
    Ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    ChartPanel Panel = new ChartPanel(Grafica2);
    JFrame Ventana = new JFrame("JFreeChart");
    Ventana.getContentPane().add(Panel);
    Ventana.pack();
    Ventana.setVisible(true);
    Ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ChartPanel Panel = new ChartPanel(Grafica3);
    JFrame Ventana = new JFrame("JFreeChart");
    Ventana.getContentPane().add(Panel);
    Ventana.pack();
    Ventana.setVisible(true);
    Ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
